#!/usr/bin/env bash
# Linux verification gate (F-13); the Linux counterpart of scripts/codex/verify.ps1. The Windows gates
# (verify-fast.ps1 / verify.ps1 / ship.ps1 on Windows, build.yml in CI) are unchanged and remain authoritative for
# the WPF product.
#
# Usage: scripts/linux/verify.sh [--fast] [--skip-restore]
#   (default)       validators + restore + Windows WPF/plugin compile check + portable builds (FlyleafLib net10.0,
#                   LLPlayer.Avalonia, LLPlayer.Avalonia.Tests) + FlyleafLibTests net10.0 + LLPlayer.Avalonia.Tests
#   --fast          validators + restore + portable builds + tests (skips the Windows WPF/plugin compile check)
#   --skip-restore  do not run dotnet restore (the restore must already be current)
# Environment:
#   LLPLAYER_FFMPEG_DIR    FFmpeg 8.1 shared libs (default: <repo>/FFmpeg/linux-x64 from fetch-ffmpeg.sh; required)
#   LLPLAYER_TEST_MEDIA    test clip (default: generated by make-test-media.sh into ~/.cache/llplayer/media)
#   LLPLAYER_FFMPEG_CLI    ffmpeg CLI for media generation (default: ~/.cache/llplayer/ffmpeg-bin/bin/ffmpeg)
#   LLPLAYER_PWSH          PowerShell 7 executable (default: pwsh on PATH, else ~/.dotnet/tools/pwsh)
#   CI=true                a missing pwsh is an error instead of a loud skip
set -euo pipefail

LLP_SCRIPT_NAME="verify"
# shellcheck source=scripts/linux/common.sh
source "$(dirname -- "${BASH_SOURCE[0]}")/common.sh"

usage() { sed -n '/^# Usage:/,/^# Environment:/p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//' >&2; }

fast=0
skip_restore=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --fast) fast=1; shift ;;
        --skip-restore) skip_restore=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) usage; llp_die "unknown argument: $1" ;;
    esac
done

cd "$LLP_REPO_ROOT"
export DOTNET_CLI_TELEMETRY_OPTOUT=1 DOTNET_NOLOGO=1
llp_require_cmd dotnet git

step() { llp_log "==> $*"; }
run() { llp_log "+ $*"; "$@"; }

# Required projects fail closed (the Linux app and its tests included).
app_proj="LLPlayer.Avalonia/LLPlayer.Avalonia.csproj"
app_tests_proj="LLPlayer.Avalonia.Tests/LLPlayer.Avalonia.Tests.csproj"
for required in LLPlayer.slnx LLPlayer/LLPlayer.csproj Plugins/YoutubeDL/YoutubeDL.csproj \
    FlyleafLib/FlyleafLib.csproj FlyleafLibTests/FlyleafLibTests.csproj "$app_proj" "$app_tests_proj"; do
    [[ -f "$required" ]] || llp_die "required project file is missing: $required"
done
for proj in "$app_proj" "$app_tests_proj"; do
    grep -qF "$proj" LLPlayer.slnx || llp_die "$proj is not listed in LLPlayer.slnx"
done

step "Linux script syntax and offline self-tests"
for script in scripts/linux/*.sh scripts/linux/tests/*.sh; do
    bash -n "$script" || llp_die "syntax error in $script"
done
if command -v shellcheck >/dev/null 2>&1; then
    run shellcheck -x scripts/linux/*.sh scripts/linux/tests/*.sh
fi
run bash scripts/linux/tests/test-scripts.sh

step "Linux FFmpeg libraries stay untracked"
tracked_so="$(git ls-files -- 'FFmpeg/linux-x64' ':(glob)**/*.so' ':(glob)**/*.so.*')"
[[ -z "$tracked_so" ]] || llp_die "Linux shared libraries must not be committed: $tracked_so"

step "Repository validators (PowerShell 7)"
pwsh_bin="${LLPLAYER_PWSH:-$(command -v pwsh || true)}"
if [[ -z "$pwsh_bin" && -x "$HOME/.dotnet/tools/pwsh" ]]; then
    pwsh_bin="$HOME/.dotnet/tools/pwsh"
fi
if [[ -n "$pwsh_bin" ]]; then
    # Platform-neutral validators. Skipped Windows-only gates:
    #  - check-environment.ps1 fails by design off Windows (WPF/WindowsDesktop verification needs Windows);
    #  - verify-plugin.ps1 self-tests an NTFS junction fixture that cannot be created on Linux;
    #  - verify-fast.ps1 / verify.ps1 / ship.ps1 wrap the two above plus the Windows publish smoke.
    for validator in verify-doc-coverage verify-frozen verify-full-gate verify-build-workflow \
        verify-release-workflow check-dub-licenses; do
        run "$pwsh_bin" -NoProfile -NonInteractive -File "scripts/codex/$validator.ps1"
    done
    # audit-frozen.ps1 is the review-routing helper, not a pass/fail gate. Without -ChangedPath it only sees the
    # working tree (empty on a clean CI checkout), so route the branch diff against origin/main when that ref exists.
    if base="$(git merge-base origin/main HEAD 2>/dev/null)" && [[ -n "$base" ]]; then
        changed_list="$(mktemp "${TMPDIR:-/tmp}/llplayer-changed.XXXXXX")"
        git diff --name-only "$base" HEAD > "$changed_list"
        if [[ -s "$changed_list" ]]; then
            llp_log "review routing for $(wc -l < "$changed_list") path(s) changed since origin/main (informational):"
            # -File cannot bind a string[] from several arguments; read the list inside PowerShell instead.
            # shellcheck disable=SC2016  # $env:... is PowerShell syntax, expanded by pwsh
            LLP_CHANGED_LIST="$changed_list" run "$pwsh_bin" -NoProfile -NonInteractive -Command \
                '& ./scripts/codex/audit-frozen.ps1 -ChangedPath @(Get-Content -LiteralPath $env:LLP_CHANGED_LIST) | Out-String -Width 250'
        fi
        rm -f "$changed_list"
    else
        llp_log "audit-frozen.ps1 (review routing helper) skipped: no origin/main merge base in this checkout."
    fi
    llp_log "skipped Windows-only gates: check-environment.ps1, verify-plugin.ps1 (and the verify-fast/verify/ship wrappers)."
elif [[ "${CI:-}" == "true" ]]; then
    llp_die "pwsh is required in CI to run the repository validators."
else
    llp_log "WARNING: pwsh not found; repository validators SKIPPED. Install it with: dotnet tool install -g PowerShell"
fi

step "Test inputs"
if [[ -z "${LLPLAYER_FFMPEG_DIR:-}" ]]; then
    export LLPLAYER_FFMPEG_DIR="$LLP_FFMPEG_DEST_DEFAULT"
fi
llp_ffmpeg_libs_present "$LLPLAYER_FFMPEG_DIR" ||
    llp_die "FFmpeg 8.1 libraries not found in $LLPLAYER_FFMPEG_DIR. Run scripts/linux/fetch-ffmpeg.sh (or set LLPLAYER_FFMPEG_DIR)."
if [[ -z "${LLPLAYER_FFMPEG_CLI:-}" && -x "$LLP_FFMPEG_BIN_DEFAULT/bin/ffmpeg" ]]; then
    export LLPLAYER_FFMPEG_CLI="$LLP_FFMPEG_BIN_DEFAULT/bin/ffmpeg"
fi
if [[ -z "${LLPLAYER_TEST_MEDIA:-}" ]]; then
    media_args=()
    [[ -n "${LLPLAYER_FFMPEG_CLI:-}" ]] && media_args+=(--ffmpeg "$LLPLAYER_FFMPEG_CLI")
    LLPLAYER_TEST_MEDIA="$(bash scripts/linux/make-test-media.sh "${media_args[@]}")"
    export LLPLAYER_TEST_MEDIA
fi
[[ -f "$LLPLAYER_TEST_MEDIA" ]] || llp_die "LLPLAYER_TEST_MEDIA does not exist: $LLPLAYER_TEST_MEDIA"
# Deterministic, device-free audio for every test run (no sound card in CI containers).
export LLPLAYER_AUDIO_BACKEND=null
llp_log "LLPLAYER_FFMPEG_DIR=$LLPLAYER_FFMPEG_DIR"
llp_log "LLPLAYER_TEST_MEDIA=$LLPLAYER_TEST_MEDIA"
llp_log "LLPLAYER_FFMPEG_CLI=${LLPLAYER_FFMPEG_CLI:-<unset>} LLPLAYER_AUDIO_BACKEND=$LLPLAYER_AUDIO_BACKEND"

if [[ $skip_restore -eq 0 ]]; then
    step "Restore"
    run dotnet restore -warnaserror LLPlayer.slnx
fi

if [[ $fast -eq 0 ]]; then
    step "Windows WPF app + plugin compile check (EnableWindowsTargeting via Directory.Build.props)"
    run dotnet build --no-restore -warnaserror LLPlayer
    run dotnet build --no-restore -warnaserror Plugins/YoutubeDL
fi

step "Portable builds"
run dotnet build --no-restore -warnaserror FlyleafLib -f net10.0
run dotnet build --no-restore -warnaserror "$app_proj"
run dotnet build --no-restore -warnaserror "$app_tests_proj"

step "Tests"
run dotnet test --no-restore -warnaserror FlyleafLibTests -f net10.0
run dotnet test --no-restore -warnaserror "$app_tests_proj"

if [[ $fast -eq 1 ]]; then
    llp_log "LLPlayer Linux fast verification completed."
else
    llp_log "LLPlayer Linux full verification completed."
fi
